import sys
import tempfile
import unittest
from pathlib import Path

from pptx import Presentation

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from render_editable_ppt import render_ppt_from_outline  # noqa: E402


class RendererTests(unittest.TestCase):
    def test_render_generates_editable_pptx_file(self):
        outline = {
            "title": "Demo Deck",
            "subtitle": "Editable output",
            "mode": "presentation",
            "theme": {
                "font_name": "Calibri",
                "title_color": "1E3A8A",
                "body_color": "0F172A",
                "accent_color": "0EA5E9",
                "background_color": "F8FAFC",
            },
            "slides": [
                {
                    "type": "title",
                    "title": "Demo Deck",
                    "subtitle": "Generated by skill",
                },
                {
                    "type": "content",
                    "title": "Key Messages",
                    "bullets": ["First point", "Second point", "Third point"],
                    "speaker_notes": "Talk through each point in 30 seconds.",
                },
            ],
        }

        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "demo.pptx"
            render_ppt_from_outline(outline, out)

            self.assertTrue(out.exists())

            pres = Presentation(str(out))
            self.assertEqual(len(pres.slides), 2)
            self.assertIn("Demo Deck", pres.slides[0].shapes.title.text)
            self.assertTrue(any(shape.has_text_frame for shape in pres.slides[1].shapes))


if __name__ == "__main__":
    unittest.main()
